spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://katalaw_bd/katalaw
    username: katalaw
    password: katalaw

  flyway:
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/postgresql
  jooq:
    sql-dialect: postgres
