CREATE SEQUENCE event_global_index;

create table ASSOCIATION_VALUE_ENTRY
(
	ID BIGINT not null
		primary key,
	ASSOCIATION_KEY VARCHAR(255) not null,
	ASSOCIATION_VALUE VARCHAR(255),
	SAGA_ID VARCHAR(255) not null,
	SAGA_TYPE VARCHAR(255)
);

create index IDXGV5K1V2MH6FRXUY5C0HGBAU94
	on ASSOCIATION_VALUE_ENTRY (SAGA_ID, SAGA_TYPE);

create index IDXK45EQNXKGD8HPDN6XIXN8SGFT
	on ASSOCIATION_VALUE_ENTRY (SAGA_TYPE, ASSOCIATION_KEY, ASSOCIATION_VALUE);

create table DOMAIN_EVENT_ENTRY
(
	GLOBAL_INDEX BIGINT DEFAULT nextval('event_global_index') not null
		primary key,
	EVENT_IDENTIFIER VARCHAR(255) not null
		unique,
	META_DATA BYTEA,
	PAYLOAD BYTEA not null,
	PAYLOAD_REVISION VARCHAR(255),
	PAYLOAD_TYPE VARCHAR(255) not null,
	TIME_STAMP VARCHAR(255) not null,
	AGGREGATE_IDENTIFIER VARCHAR(255) not null,
	SEQUENCE_NUMBER BIGINT not null,
	TYPE VARCHAR(255),
	unique (AGGREGATE_IDENTIFIER, SEQUENCE_NUMBER)
);

create table SAGA_ENTRY
(
	SAGA_ID VARCHAR(255) not null
		primary key,
	REVISION VARCHAR(255),
	SAGA_TYPE VARCHAR(255),
	SERIALIZED_SAGA BYTEA
);

create table SNAPSHOT_EVENT_ENTRY
(
	AGGREGATE_IDENTIFIER VARCHAR(255) not null,
	SEQUENCE_NUMBER BIGINT not null,
	TYPE VARCHAR(255) not null,
	EVENT_IDENTIFIER VARCHAR(255) not null
		unique,
	META_DATA BYTEA,
	PAYLOAD BYTEA not null,
	PAYLOAD_REVISION VARCHAR(255),
	PAYLOAD_TYPE VARCHAR(255) not null,
	TIME_STAMP VARCHAR(255) not null,
	primary key (AGGREGATE_IDENTIFIER, SEQUENCE_NUMBER, TYPE)
);

create table TOKEN_ENTRY
(
	PROCESSOR_NAME VARCHAR(255) not null,
	SEGMENT INTEGER not null,
	OWNER VARCHAR(255),
	TIMESTAMP VARCHAR(255) not null,
	TOKEN BYTEA,
	TOKEN_TYPE VARCHAR(255),
	primary key (PROCESSOR_NAME, SEGMENT)
);
